# simple IOS config in ansible
---
- name: Sample IOS playbook for Ansible core 2.12
  hosts: iosxe

  tasks:
  - name: set ACL via CLI
    cisco.ios.ios_config:
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended my_acl']
      before: no ip access-list extended my_acl

  - name: Configure the login banner
    cisco.ios.ios_banner:
      banner: login
      text: this is my login banner
      state: present